### ISSUE TITLE
Feature request: openrouter and custom openai url support

### ISSUE THREAD

**Issue by lrq3000** [giulioco/openpod#1]
Would it be possible to add support for the openrouter api? Not only wiuld this allow to be future proof and support current and future llm providers, but also some models are free.

Alternatively I would like to suggest to allow to define a custom URL for the openai API, because this would allow to support self hosted, local LLM servers such as ollama that expose OpenAI-compatible APIs, without modifying your codebase at all.

**Comment by giulioco** [comment]
The LLMs are handled by Podcastfy so you should open an issue there instead. This library only adds a UI for the Podcastfy library
